WITH frontend (fn_name) AS (
    VALUES
    ('fn_activate_user'),
    ('fn_advance_term_status'),
    ('fn_bulk_create_programs'),
    ('fn_bulk_delete_announcements'),
    ('fn_bulk_delete_courses'),
    ('fn_bulk_delete_departments'),
    ('fn_bulk_delete_events'),
    ('fn_bulk_delete_programs'),
    ('fn_bulk_delete_sections'),
    ('fn_bulk_delete_students'),
    ('fn_bulk_delete_users'),
    ('fn_bulk_enroll_student'),
    ('fn_bulk_provision_users'),
    ('fn_calculate_all_grades_for_period'),
    ('fn_change_student_status'),
    ('fn_copy_rubric_to_sections'),
    ('fn_copy_section_setup_to_sections'),
    ('fn_create_announcement'),
    ('fn_create_assessment'),
    ('fn_create_assessment_attachment'),
    ('fn_create_attendance_session'),
    ('fn_create_course'),
    ('fn_create_course_type'),
    ('fn_create_curriculum_map_entry'),
    ('fn_create_department'),
    ('fn_create_evaluation_template'),
    ('fn_create_event'),
    ('fn_create_grading_component'),
    ('fn_create_grading_period_template'),
    ('fn_create_material'),
    ('fn_create_module'),
    ('fn_create_program'),
    ('fn_create_program_level'),
    ('fn_create_role'),
    ('fn_create_rubric'),
    ('fn_create_school_year'),
    ('fn_create_section'),
    ('fn_create_student'),
    ('fn_create_term'),
    ('fn_create_term_type'),
    ('fn_create_thread'),
    ('fn_delete_announcement'),
    ('fn_delete_assessment'),
    ('fn_delete_assessment_attachment'),
    ('fn_delete_attendance_session'),
    ('fn_delete_course'),
    ('fn_delete_course_type'),
    ('fn_delete_curriculum_map_entry'),
    ('fn_delete_department'),
    ('fn_delete_evaluation_template'),
    ('fn_delete_event'),
    ('fn_delete_grading_component'),
    ('fn_delete_grading_period_template'),
    ('fn_delete_material'),
    ('fn_delete_module'),
    ('fn_delete_post'),
    ('fn_delete_program'),
    ('fn_delete_program_level'),
    ('fn_delete_question'),
    ('fn_delete_role'),
    ('fn_delete_rubric'),
    ('fn_delete_school_year'),
    ('fn_delete_section'),
    ('fn_delete_special_grade_config'),
    ('fn_delete_student'),
    ('fn_delete_term'),
    ('fn_delete_term_type'),
    ('fn_delete_thread'),
    ('fn_drop_enrollment'),
    ('fn_duplicate_assessment_to_sections'),
    ('fn_duplicate_module_to_sections'),
    ('fn_evaluate_student_year_level'),
    ('fn_get_academic_thresholds'),
    ('fn_get_admin_dashboard_stats'),
    ('fn_get_announcement_by_id'),
    ('fn_get_announcement_section_options'),
    ('fn_get_assessment_by_id'),
    ('fn_get_assessment_for_student'),
    ('fn_get_assessment_item_analysis'),
    ('fn_get_assessment_questions'),
    ('fn_get_assessment_questions_for_student'),
    ('fn_get_assessment_rubric'),
    ('fn_get_attendance_records'),
    ('fn_get_audit_log_tables'),
    ('fn_get_auth_context'),
    ('fn_get_course_by_id'),
    ('fn_get_course_type_by_id'),
    ('fn_get_course_types'),
    ('fn_get_courses'),
    ('fn_get_curriculum_audit'),
    ('fn_get_curriculum_map'),
    ('fn_get_dean_dashboard'),
    ('fn_get_department_by_id'),
    ('fn_get_departments'),
    ('fn_get_discussion_thread'),
    ('fn_get_enrollment_student_detail'),
    ('fn_get_enrollment_target_term'),
    ('fn_get_evaluation_form'),
    ('fn_get_evaluation_templates'),
    ('fn_get_event_by_id'),
    ('fn_get_faculty_dashboard'),
    ('fn_get_faculty_dean_users'),
    ('fn_get_faculty_load_detail'),
    ('fn_get_grading_period_templates'),
    ('fn_get_my_assessment_result'),
    ('fn_get_my_profile'),
    ('fn_get_program_by_id'),
    ('fn_get_program_level_by_id'),
    ('fn_get_program_levels'),
    ('fn_get_programs'),
    ('fn_get_registrar_dashboard'),
    ('fn_get_role_by_id'),
    ('fn_get_roles'),
    ('fn_get_rubric'),
    ('fn_get_school_year_by_id'),
    ('fn_get_school_years'),
    ('fn_get_section_by_id'),
    ('fn_get_section_content'),
    ('fn_get_section_detail'),
    ('fn_get_section_insight'),
    ('fn_get_section_student_evaluation'),
    ('fn_get_sections'),
    ('fn_get_special_grade_configs'),
    ('fn_get_student_attendance'),
    ('fn_get_student_by_id'),
    ('fn_get_student_dashboard'),
    ('fn_get_student_grade_breakdown'),
    ('fn_get_student_insight'),
    ('fn_get_student_schedule'),
    ('fn_get_student_transcript'),
    ('fn_get_students'),
    ('fn_get_subject_assessments'),
    ('fn_get_subject_detail'),
    ('fn_get_subject_grades'),
    ('fn_get_submission_for_grading'),
    ('fn_get_submission_rubric'),
    ('fn_get_system_settings'),
    ('fn_get_term_by_id'),
    ('fn_get_term_type_by_id'),
    ('fn_get_term_types'),
    ('fn_get_terms'),
    ('fn_get_transmutation_table'),
    ('fn_get_unread_notification_count'),
    ('fn_get_user_by_id'),
    ('fn_get_users_by_roles'),
    ('fn_grade_submission'),
    ('fn_grade_submission_rubric'),
    ('fn_is_section_grading_locked'),
    ('fn_list_announcements_json'),
    ('fn_list_assessments'),
    ('fn_list_attendance_sessions'),
    ('fn_list_course_types_json'),
    ('fn_list_courses_json'),
    ('fn_list_departments_json'),
    ('fn_list_eligible_sections'),
    ('fn_list_enrollment_students_json'),
    ('fn_list_events_json'),
    ('fn_list_faculty_load_json'),
    ('fn_list_grade_audit_logs_json'),
    ('fn_list_grade_release_schedule'),
    ('fn_list_grade_sheet'),
    ('fn_list_grading_components'),
    ('fn_list_grading_periods_by_section'),
    ('fn_list_my_announcements_feed'),
    ('fn_list_my_events_feed'),
    ('fn_list_my_grades'),
    ('fn_list_my_notifications_json'),
    ('fn_list_my_sections'),
    ('fn_list_my_subjects'),
    ('fn_list_my_teaching_sections'),
    ('fn_list_program_levels_json'),
    ('fn_list_programs_json'),
    ('fn_list_roles_json'),
    ('fn_list_rubrics'),
    ('fn_list_schedule_conflicts'),
    ('fn_list_school_years_json'),
    ('fn_list_section_students'),
    ('fn_list_section_threads_json'),
    ('fn_list_sections_json'),
    ('fn_list_student_lifecycle_events'),
    ('fn_list_students_json'),
    ('fn_list_submissions'),
    ('fn_list_term_types_json'),
    ('fn_list_terms_json'),
    ('fn_list_users_json'),
    ('fn_mark_material_complete'),
    ('fn_mark_my_notifications_read'),
    ('fn_provision_single_user'),
    ('fn_publish_assessment'),
    ('fn_record_heartbeat'),
    ('fn_release_grading_period_now'),
    ('fn_reply_to_thread'),
    ('fn_reseed_section_grading'),
    ('fn_save_attendance_records'),
    ('fn_save_special_grade_configs'),
    ('fn_save_student_answer'),
    ('fn_save_student_answer_files'),
    ('fn_save_transmutation_table'),
    ('fn_set_assessment_rubric'),
    ('fn_set_grading_period_release_at'),
    ('fn_set_material_published'),
    ('fn_set_module_published'),
    ('fn_set_post_answer'),
    ('fn_set_thread_pinned'),
    ('fn_set_thread_resolved'),
    ('fn_shift_student_program'),
    ('fn_start_assessment_timer'),
    ('fn_submit_assessment'),
    ('fn_submit_evaluation'),
    ('fn_unpublish_assessment'),
    ('fn_update_academic_thresholds'),
    ('fn_update_announcement'),
    ('fn_update_assessment'),
    ('fn_update_course'),
    ('fn_update_course_type'),
    ('fn_update_curriculum_map_entry'),
    ('fn_update_department'),
    ('fn_update_evaluation_template'),
    ('fn_update_event'),
    ('fn_update_grading_component'),
    ('fn_update_grading_period_template'),
    ('fn_update_material'),
    ('fn_update_module'),
    ('fn_update_my_profile'),
    ('fn_update_program'),
    ('fn_update_program_level'),
    ('fn_update_role'),
    ('fn_update_rubric'),
    ('fn_update_school_year'),
    ('fn_update_section'),
    ('fn_update_student'),
    ('fn_update_system_settings'),
    ('fn_update_term'),
    ('fn_update_term_type'),
    ('fn_update_user'),
    ('fn_upsert_question'),
    ('fn_upsert_student_section_color')
),
live AS (
    SELECT
        p.proname AS fn_name,
        count(*) AS overloads,
        bool_or(p.prosecdef) AS has_definer
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
        AND p.proname LIKE 'fn\_%'
    GROUP BY p.proname
),
missing AS (
    SELECT f.fn_name
    FROM frontend f
    LEFT JOIN live l ON l.fn_name = f.fn_name
    WHERE l.fn_name IS NULL
),
orphaned AS (
    SELECT l.fn_name
    FROM live l
    LEFT JOIN frontend f ON f.fn_name = l.fn_name
    WHERE f.fn_name IS NULL
)
SELECT '1_SUMMARY' AS kind, 'frontend_calls=' || (SELECT count(*) FROM frontend)
    || ' live_fns=' || (SELECT count(*) FROM live)
    || ' missing_in_db=' || (SELECT count(*) FROM missing)
    || ' unused_in_db=' || (SELECT count(*) FROM orphaned) AS detail
UNION ALL
SELECT '2_MISSING_IN_DB', fn_name FROM missing
UNION ALL
SELECT '3_UNUSED_IN_DB', fn_name FROM orphaned
UNION ALL
SELECT '4_PASTE_BACK', 'MISSING: ' || coalesce((SELECT string_agg(fn_name, ',' ORDER BY fn_name) FROM missing), 'none')
UNION ALL
SELECT '5_PASTE_BACK', 'UNUSED: ' || coalesce((SELECT string_agg(fn_name, ',' ORDER BY fn_name) FROM orphaned), 'none')
ORDER BY 1, 2
