import { runQuery } from './query.mjs';

const coursesToCreate = [
  // =========================================================
  // 1. CITE (College of Information Technology) - 30 Courses
  // =========================================================
  { code: 'GCAS 01', title: 'Art Appreciation', department_code: 'CITE', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'General education art appreciation and aesthetic study', is_active: 'true', prerequisites: '' },
  { code: 'GCAS 02', title: 'Ethics', department_code: 'CITE', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Moral philosophy and professional ethical principles', is_active: 'true', prerequisites: '' },
  { code: 'GCAS 03', title: 'Purposive Communication', department_code: 'CITE', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Multimodal communication and academic writing', is_active: 'true', prerequisites: '' },
  { code: 'GCAS 04', title: 'Readings in Philippine History', department_code: 'CITE', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Critical analysis of Philippine historical records', is_active: 'true', prerequisites: '' },
  { code: 'GCAS 05', title: 'The Contemporary World', department_code: 'CITE', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Globalization and contemporary global structures', is_active: 'true', prerequisites: '' },
  { code: 'GCAS 06', title: 'Science Technology and Society', department_code: 'CITE', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Interactions between scientific advancements and human society', is_active: 'true', prerequisites: '' },
  { code: 'GCAS 07', title: 'Mathematics in the Modern World', department_code: 'CITE', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Nature of mathematics and practical applications', is_active: 'true', prerequisites: '' },
  { code: 'GCAS 08', title: 'Understanding the Self', department_code: 'CITE', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Personal identity and psychological self-awareness', is_active: 'true', prerequisites: '' },
  { code: 'GCAS 09', title: 'Life and Works of Rizal', department_code: 'CITE', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Biography and literary works of Jose Rizal', is_active: 'true', prerequisites: '' },
  { code: 'GCAS 15', title: 'PE-1 Physical Fitness and Health', department_code: 'CITE', course_type_code: 'PE', lecture_units: '2', laboratory_units: '0', credit_hours: '2', description: 'Physical wellness and fitness fundamental movements', is_active: 'true', prerequisites: '' },
  { code: 'GCAS 16', title: 'PE-2 Fitness Exercises', department_code: 'CITE', course_type_code: 'PE', lecture_units: '2', laboratory_units: '0', credit_hours: '2', description: 'Rhythmic activities and motor skill development', is_active: 'true', prerequisites: '' },
  { code: 'GCAS 17', title: 'PE-3 Individual and Dual Sports', department_code: 'CITE', course_type_code: 'PE', lecture_units: '2', laboratory_units: '0', credit_hours: '2', description: 'Rules and techniques of individual sports', is_active: 'true', prerequisites: '' },
  { code: 'GCAS 18', title: 'PE-4 Team Sports', department_code: 'CITE', course_type_code: 'PE', lecture_units: '2', laboratory_units: '0', credit_hours: '2', description: 'Team sports strategies and physical education', is_active: 'true', prerequisites: '' },
  { code: 'GCAS 19', title: 'NSTP 1', department_code: 'CITE', course_type_code: 'NSTP', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Civic welfare and national service training phase 1', is_active: 'true', prerequisites: '' },
  { code: 'GCAS 20', title: 'NSTP 2', department_code: 'CITE', course_type_code: 'NSTP', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Community literacy and national service training phase 2', is_active: 'true', prerequisites: 'GCAS 19:Required:3.0' },
  { code: 'CS 101LEC', title: 'Computer Programming 1 (LEC)', department_code: 'CITE', course_type_code: 'LECTURE', lecture_units: '2', laboratory_units: '0', credit_hours: '2', description: 'Introduction to algorithmic thinking and procedural programming', is_active: 'true', prerequisites: '' },
  { code: 'CS 101LAB', title: 'Computer Programming 1 (LAB)', department_code: 'CITE', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '1', credit_hours: '1', description: 'Practical coding lab for programming fundamentals', is_active: 'true', prerequisites: '' },
  { code: 'CS 102LEC', title: 'Computer Programming 2 (LEC)', department_code: 'CITE', course_type_code: 'LECTURE', lecture_units: '2', laboratory_units: '0', credit_hours: '2', description: 'Advanced procedural and modular programming techniques', is_active: 'true', prerequisites: 'CS 101LEC:Required:2.0' },
  { code: 'CS 102LAB', title: 'Computer Programming 2 (LAB)', department_code: 'CITE', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '1', credit_hours: '1', description: 'Coding laboratory for intermediate programming', is_active: 'true', prerequisites: 'CS 101LAB:Required:2.0' },
  { code: 'CS 201LEC', title: 'Data Structures and Algorithms (LEC)', department_code: 'CITE', course_type_code: 'LECTURE', lecture_units: '2', laboratory_units: '0', credit_hours: '2', description: 'Linear and non-linear data structures analysis', is_active: 'true', prerequisites: 'CS 102LEC:Required:2.0' },
  { code: 'CS 201LAB', title: 'Data Structures and Algorithms (LAB)', department_code: 'CITE', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '1', credit_hours: '1', description: 'Implementation laboratory for data structures', is_active: 'true', prerequisites: 'CS 102LAB:Required:2.0' },
  { code: 'CS 202', title: 'Design and Analysis of Algorithms', department_code: 'CITE', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Algorithm design strategies and asymptotic complexity', is_active: 'true', prerequisites: 'CS 201LEC:Required:2.0' },
  { code: 'CS 301LEC', title: 'Database Management Systems (LEC)', department_code: 'CITE', course_type_code: 'LECTURE', lecture_units: '2', laboratory_units: '0', credit_hours: '2', description: 'Relational database model and SQL design', is_active: 'true', prerequisites: 'CS 102LEC:Required:2.0' },
  { code: 'CS 301LAB', title: 'Database Management Systems (LAB)', department_code: 'CITE', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '1', credit_hours: '1', description: 'Hands-on database schema design and SQL querying', is_active: 'true', prerequisites: 'CS 102LAB:Required:2.0' },
  { code: 'CS 302LEC', title: 'Web Development (LEC)', department_code: 'CITE', course_type_code: 'LECTURE', lecture_units: '2', laboratory_units: '0', credit_hours: '2', description: 'Client-server web architecture and frontend development', is_active: 'true', prerequisites: 'CS 102LEC:Required:2.0' },
  { code: 'CS 302LAB', title: 'Web Development (LAB)', department_code: 'CITE', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '1', credit_hours: '1', description: 'Web development lab with HTML CSS JS and frameworks', is_active: 'true', prerequisites: 'CS 102LAB:Required:2.0' },
  { code: 'CS 303', title: 'Computer Networks', department_code: 'CITE', course_type_code: 'LECTURE_LAB', lecture_units: '2', laboratory_units: '1', credit_hours: '3', description: 'OSI model network protocols and socket programming', is_active: 'true', prerequisites: 'CS 201LEC:Required:2.0' },
  { code: 'CS 304', title: 'Operating Systems', department_code: 'CITE', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Process management memory allocation and concurrency', is_active: 'true', prerequisites: 'CS 201LEC:Required:2.0' },
  { code: 'CS 401', title: 'Capstone Project 1 (Thesis 1)', department_code: 'CITE', course_type_code: 'THESIS', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Research proposal and software requirement specification', is_active: 'true', prerequisites: 'CS 301LEC:Required:2.0' },
  { code: 'CS 402', title: 'Capstone Project 2 (Thesis 2)', department_code: 'CITE', course_type_code: 'THESIS', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'System implementation testing and final oral defense', is_active: 'true', prerequisites: 'CS 401:Required:2.0' },

  // =========================================================
  // 2. BSN (Bachelor of Science in Nursing) - 30 Courses
  // =========================================================
  { code: 'NURS 101LEC', title: 'Anatomy and Physiology (LEC)', department_code: 'BSN', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Human body structure and physiological functions', is_active: 'true', prerequisites: '' },
  { code: 'NURS 101LAB', title: 'Anatomy and Physiology (LAB)', department_code: 'BSN', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '2', credit_hours: '2', description: 'Anatomical dissection and physiological lab exercises', is_active: 'true', prerequisites: '' },
  { code: 'NURS 102', title: 'Biochemistry for Health Sciences', department_code: 'BSN', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Chemical processes within living organisms relevant to health', is_active: 'true', prerequisites: '' },
  { code: 'NURS 103', title: 'Theoretical Foundations of Nursing', department_code: 'BSN', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Nursing theories conceptual frameworks and history', is_active: 'true', prerequisites: '' },
  { code: 'NURS 104LEC', title: 'Fundamentals of Nursing Practice (LEC)', department_code: 'BSN', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Basic nursing concepts procedures and patient care fundamentals', is_active: 'true', prerequisites: 'NURS 101LEC:Required:2.0' },
  { code: 'NURS 104LAB', title: 'Fundamentals of Nursing Practice (LAB)', department_code: 'BSN', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '2', credit_hours: '2', description: 'Skills lab for essential clinical nursing procedures', is_active: 'true', prerequisites: 'NURS 101LAB:Required:2.0' },
  { code: 'NURS 201LEC', title: 'Health Assessment (LEC)', department_code: 'BSN', course_type_code: 'LECTURE', lecture_units: '2', laboratory_units: '0', credit_hours: '2', description: 'Comprehensive physical examination and patient health history', is_active: 'true', prerequisites: 'NURS 104LEC:Required:2.0' },
  { code: 'NURS 201LAB', title: 'Health Assessment (LAB)', department_code: 'BSN', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '1', credit_hours: '1', description: 'Practical health assessment and physical exam laboratory', is_active: 'true', prerequisites: 'NURS 104LAB:Required:2.0' },
  { code: 'NURS 202', title: 'Pharmacology in Nursing', department_code: 'BSN', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Pharmacodynamics dosage calculation and medication administration', is_active: 'true', prerequisites: 'NURS 101LEC:Required:2.0' },
  { code: 'NURS 203', title: 'Nutrition and Diet Therapy', department_code: 'BSN', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Nutritional principles and therapeutic diets for patient conditions', is_active: 'true', prerequisites: 'NURS 102:Required:2.0' },
  { code: 'NURS 204LEC', title: 'Microbiology and Parasitology (LEC)', department_code: 'BSN', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Pathogenic microorganisms infectious disease transmission and control', is_active: 'true', prerequisites: 'NURS 101LEC:Required:2.0' },
  { code: 'NURS 204LAB', title: 'Microbiology and Parasitology (LAB)', department_code: 'BSN', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '1', credit_hours: '1', description: 'Microbiology lab techniques staining and microscopy', is_active: 'true', prerequisites: 'NURS 101LAB:Required:2.0' },
  { code: 'NURS 205LEC', title: 'Care of Mother, Child and Adolescent (LEC)', department_code: 'BSN', course_type_code: 'LECTURE', lecture_units: '4', laboratory_units: '0', credit_hours: '4', description: 'Maternal-child nursing care obstetrics and pediatrics', is_active: 'true', prerequisites: 'NURS 201LEC:Required:2.0' },
  { code: 'NURS 205LAB', title: 'Care of Mother, Child and Adolescent (LAB)', department_code: 'BSN', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '3', credit_hours: '3', description: 'Clinical hospital practicum in obstetric and pediatric wards', is_active: 'true', prerequisites: 'NURS 201LAB:Required:2.0' },
  { code: 'NURS 301LEC', title: 'Care of Clients with Oxygenation & Fluid Imbalance (LEC)', department_code: 'BSN', course_type_code: 'LECTURE', lecture_units: '4', laboratory_units: '0', credit_hours: '4', description: 'Medical-surgical nursing for respiratory cardiac and renal disorders', is_active: 'true', prerequisites: 'NURS 205LEC:Required:2.0' },
  { code: 'NURS 301LAB', title: 'Clinical Practicum in Medical-Surgical 1', department_code: 'BSN', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '3', credit_hours: '3', description: 'Medical-surgical clinical ward rotation phase 1', is_active: 'true', prerequisites: 'NURS 205LAB:Required:2.0' },
  { code: 'NURS 302LEC', title: 'Care of Clients with Inflammatory & Immunologic Response', department_code: 'BSN', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Immune response management and infectious disease nursing', is_active: 'true', prerequisites: 'NURS 301LEC:Required:2.0' },
  { code: 'NURS 302LAB', title: 'Clinical Practicum in Medical-Surgical 2', department_code: 'BSN', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '3', credit_hours: '3', description: 'Medical-surgical clinical ward rotation phase 2', is_active: 'true', prerequisites: 'NURS 301LAB:Required:2.0' },
  { code: 'NURS 303', title: 'Nursing Informatics', department_code: 'BSN', course_type_code: 'LECTURE_LAB', lecture_units: '2', laboratory_units: '1', credit_hours: '3', description: 'Health Information Technology and electronic health records in nursing', is_active: 'true', prerequisites: '' },
  { code: 'NURS 304LEC', title: 'Care of Clients with Maladaptive Behavior (LEC)', department_code: 'BSN', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Psychiatric and mental health nursing concepts', is_active: 'true', prerequisites: 'NURS 201LEC:Required:2.0' },
  { code: 'NURS 304LAB', title: 'Psychiatric Nursing Clinical Practicum', department_code: 'BSN', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '2', credit_hours: '2', description: 'Clinical rotation in psychiatric units and mental health institutions', is_active: 'true', prerequisites: 'NURS 201LAB:Required:2.0' },
  { code: 'NURS 305', title: 'Nursing Research 1', department_code: 'BSN', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Research methodology problem identification and literature review', is_active: 'true', prerequisites: 'NURS 201LEC:Required:2.0' },
  { code: 'NURS 306', title: 'Nursing Research 2', department_code: 'BSN', course_type_code: 'THESIS', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Data collection analysis and defense of nursing research paper', is_active: 'true', prerequisites: 'NURS 305:Required:2.0' },
  { code: 'NURS 401LEC', title: 'Care of Clients with Cellular Aberrations (LEC)', department_code: 'BSN', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Oncology critical care and complex multidimensional disorders', is_active: 'true', prerequisites: 'NURS 302LEC:Required:2.0' },
  { code: 'NURS 401LAB', title: 'Advanced Clinical Practicum', department_code: 'BSN', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '3', credit_hours: '3', description: 'Specialty ward rotation in ICU emergency room and OR', is_active: 'true', prerequisites: 'NURS 302LAB:Required:2.0' },
  { code: 'NURS 402', title: 'Disaster Nursing and Emergency Care', department_code: 'BSN', course_type_code: 'LECTURE_LAB', lecture_units: '2', laboratory_units: '1', credit_hours: '3', description: 'Triage emergency response and disaster management protocols', is_active: 'true', prerequisites: 'NURS 301LEC:Required:2.0' },
  { code: 'NURS 403', title: 'Nursing Leadership and Management', department_code: 'BSN', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Ward management organizational leadership and quality improvement', is_active: 'true', prerequisites: 'NURS 302LEC:Required:2.0' },
  { code: 'NURS 404', title: 'Intensive Clinical Practicum (OJT)', department_code: 'BSN', course_type_code: 'OJT', lecture_units: '0', laboratory_units: '5', credit_hours: '5', description: 'Comprehensive hospital duty and clinical internship', is_active: 'true', prerequisites: 'NURS 401LEC:Required:2.0' },
  { code: 'NURS 405', title: 'Community Health Nursing 1', department_code: 'BSN', course_type_code: 'LECTURE_LAB', lecture_units: '2', laboratory_units: '2', credit_hours: '4', description: 'Public health epidemiology and primary health care delivery', is_active: 'true', prerequisites: 'NURS 205LEC:Required:2.0' },
  { code: 'NURS 406', title: 'Community Health Nursing 2', department_code: 'BSN', course_type_code: 'LECTURE_LAB', lecture_units: '2', laboratory_units: '2', credit_hours: '4', description: 'Community diagnosis health program planning and field immersion', is_active: 'true', prerequisites: 'NURS 405:Required:2.0' },

  // =========================================================
  // 3. MDTCH (Medical Technology) - 30 Courses
  // =========================================================
  { code: 'MEDT 101', title: 'Introduction to Medical Laboratory Science', department_code: 'MDTCH', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Overview of medical laboratory science career ethics and safety', is_active: 'true', prerequisites: '' },
  { code: 'MEDT 102LEC', title: 'Human Anatomy and Physiology for MedTech (LEC)', department_code: 'MDTCH', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Human organ systems histology and systemic physiology', is_active: 'true', prerequisites: '' },
  { code: 'MEDT 102LAB', title: 'Human Anatomy and Physiology for MedTech (LAB)', department_code: 'MDTCH', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '2', credit_hours: '2', description: 'Anatomical model study and laboratory experiments', is_active: 'true', prerequisites: '' },
  { code: 'MEDT 103', title: 'Principles of Medical Laboratory Science 1', department_code: 'MDTCH', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Laboratory safety glasswares centrifugation and phlebotomy basics', is_active: 'true', prerequisites: '' },
  { code: 'MEDT 104', title: 'Principles of Medical Laboratory Science 2', department_code: 'MDTCH', course_type_code: 'LECTURE_LAB', lecture_units: '2', laboratory_units: '1', credit_hours: '3', description: 'Phlebotomy technique specimen collection processing and quality control', is_active: 'true', prerequisites: 'MEDT 103:Required:2.0' },
  { code: 'MEDT 201LEC', title: 'Clinical Chemistry 1 (LEC)', department_code: 'MDTCH', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Analysis of carbohydrates lipids proteins and enzymes in serum', is_active: 'true', prerequisites: 'MEDT 102LEC:Required:2.0' },
  { code: 'MEDT 201LAB', title: 'Clinical Chemistry 1 (LAB)', department_code: 'MDTCH', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '2', credit_hours: '2', description: 'Spectrophotometry and chemical testing of serum analytes', is_active: 'true', prerequisites: 'MEDT 102LAB:Required:2.0' },
  { code: 'MEDT 202LEC', title: 'Clinical Chemistry 2 (LEC)', department_code: 'MDTCH', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Endocrinology toxicology therapeutic drug monitoring and electrolytes', is_active: 'true', prerequisites: 'MEDT 201LEC:Required:2.0' },
  { code: 'MEDT 202LAB', title: 'Clinical Chemistry 2 (LAB)', department_code: 'MDTCH', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '2', credit_hours: '2', description: 'Advanced clinical chemistry instrumentation and electrolyte testing', is_active: 'true', prerequisites: 'MEDT 201LAB:Required:2.0' },
  { code: 'MEDT 203LEC', title: 'Clinical Microscopy (LEC)', department_code: 'MDTCH', course_type_code: 'LECTURE', lecture_units: '2', laboratory_units: '0', credit_hours: '2', description: 'Urinalysis and body fluid examination principles', is_active: 'true', prerequisites: 'MEDT 102LEC:Required:2.0' },
  { code: 'MEDT 203LAB', title: 'Clinical Microscopy (LAB)', department_code: 'MDTCH', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '1', credit_hours: '1', description: 'Microscopic examination of urine CSF and body fluids', is_active: 'true', prerequisites: 'MEDT 102LAB:Required:2.0' },
  { code: 'MEDT 204LEC', title: 'Immunology and Serology (LEC)', department_code: 'MDTCH', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Immune mechanisms antibody production and serological assays', is_active: 'true', prerequisites: 'MEDT 102LEC:Required:2.0' },
  { code: 'MEDT 204LAB', title: 'Immunology and Serology (LAB)', department_code: 'MDTCH', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '1', credit_hours: '1', description: 'Agglutination precipitation and ELISA lab techniques', is_active: 'true', prerequisites: 'MEDT 102LAB:Required:2.0' },
  { code: 'MEDT 205LEC', title: 'Hematology 1 (LEC)', department_code: 'MDTCH', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Blood cell formation maturation and non-malignant disorders', is_active: 'true', prerequisites: 'MEDT 102LEC:Required:2.0' },
  { code: 'MEDT 205LAB', title: 'Hematology 1 (LAB)', department_code: 'MDTCH', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '2', credit_hours: '2', description: 'Complete blood count blood smearing and cell differential count', is_active: 'true', prerequisites: 'MEDT 102LAB:Required:2.0' },
  { code: 'MEDT 301LEC', title: 'Hematology 2 (LEC)', department_code: 'MDTCH', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Hemostasis coagulation disorders and hematologic malignancies', is_active: 'true', prerequisites: 'MEDT 205LEC:Required:2.0' },
  { code: 'MEDT 301LAB', title: 'Hematology 2 (LAB)', department_code: 'MDTCH', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '1', credit_hours: '1', description: 'Coagulation testing PT PTT and bone marrow smear analysis', is_active: 'true', prerequisites: 'MEDT 205LAB:Required:2.0' },
  { code: 'MEDT 302LEC', title: 'Immunohematology / Blood Banking (LEC)', department_code: 'MDTCH', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'ABO and Rh blood grouping donor screening and transfusion safety', is_active: 'true', prerequisites: 'MEDT 204LEC:Required:2.0' },
  { code: 'MEDT 302LAB', title: 'Immunohematology / Blood Banking (LAB)', department_code: 'MDTCH', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '1', credit_hours: '1', description: 'Crossmatching blood typing and Coomb test procedures', is_active: 'true', prerequisites: 'MEDT 204LAB:Required:2.0' },
  { code: 'MEDT 303LEC', title: 'Clinical Bacteriology (LEC)', department_code: 'MDTCH', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Identification isolation and antibiotic susceptibility testing of bacteria', is_active: 'true', prerequisites: 'MEDT 102LEC:Required:2.0' },
  { code: 'MEDT 303LAB', title: 'Clinical Bacteriology (LAB)', department_code: 'MDTCH', course_type_code: 'LABORATORY', lecture_units: '0', laboratory_units: '2', credit_hours: '2', description: 'Bacterial culture media preparation biochemical testing and Gram stain', is_active: 'true', prerequisites: 'MEDT 102LAB:Required:2.0' },
  { code: 'MEDT 304', title: 'Clinical Parasitology', department_code: 'MDTCH', course_type_code: 'LECTURE_LAB', lecture_units: '2', laboratory_units: '1', credit_hours: '3', description: 'Intestinal and blood parasites lifecycle and diagnostic techniques', is_active: 'true', prerequisites: 'MEDT 102LEC:Required:2.0' },
  { code: 'MEDT 305', title: 'Mycology and Virology', department_code: 'MDTCH', course_type_code: 'LECTURE', lecture_units: '2', laboratory_units: '0', credit_hours: '2', description: 'Fungal and viral pathogens clinical manifestations and diagnostics', is_active: 'true', prerequisites: 'MEDT 303LEC:Required:2.0' },
  { code: 'MEDT 306', title: 'Histopathologic Techniques and Cytology', department_code: 'MDTCH', course_type_code: 'LECTURE_LAB', lecture_units: '2', laboratory_units: '1', credit_hours: '3', description: 'Tissue processing microtomy Pap smear staining and biopsy procedures', is_active: 'true', prerequisites: 'MEDT 102LEC:Required:2.0' },
  { code: 'MEDT 401', title: 'Clinical Internship 1', department_code: 'MDTCH', course_type_code: 'OJT', lecture_units: '0', laboratory_units: '6', credit_hours: '6', description: 'Hospital laboratory rotation phase 1 in accredited hospital labs', is_active: 'true', prerequisites: 'MEDT 301LEC:Required:2.0' },
  { code: 'MEDT 402', title: 'Clinical Internship 2', department_code: 'MDTCH', course_type_code: 'OJT', lecture_units: '0', laboratory_units: '6', credit_hours: '6', description: 'Hospital laboratory rotation phase 2 in accredited hospital labs', is_active: 'true', prerequisites: 'MEDT 401:Required:2.0' },
  { code: 'MEDT 403', title: 'Molecular Biology and Diagnostics', department_code: 'MDTCH', course_type_code: 'LECTURE_LAB', lecture_units: '2', laboratory_units: '1', credit_hours: '3', description: 'PCR nucleic acid amplification and molecular testing techniques', is_active: 'true', prerequisites: 'MEDT 201LEC:Required:2.0' },
  { code: 'MEDT 404', title: 'Laboratory Management and Quality Control', department_code: 'MDTCH', course_type_code: 'LECTURE', lecture_units: '2', laboratory_units: '0', credit_hours: '2', description: 'Laboratory leadership accreditation biosafety and quality assurance', is_active: 'true', prerequisites: '' },
  { code: 'MEDT 405', title: 'Medical Technology Seminar 1', department_code: 'MDTCH', course_type_code: 'LECTURE', lecture_units: '2', laboratory_units: '0', credit_hours: '2', description: 'Comprehensive review and case studies in clinical pathology', is_active: 'true', prerequisites: 'MEDT 301LEC:Required:2.0' },
  { code: 'MEDT 406', title: 'Medical Technology Seminar 2', department_code: 'MDTCH', course_type_code: 'LECTURE', lecture_units: '2', laboratory_units: '0', credit_hours: '2', description: 'Licensure examination preparation and integrative review', is_active: 'true', prerequisites: 'MEDT 405:Required:2.0' },

  // =========================================================
  // 4. AB POLSCI (Bachelor of Arts in Political Science) - 30 Courses
  // =========================================================
  { code: 'POLS 101', title: 'Introduction to Political Science', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Concepts of state power authority legitimacy and political ideologies', is_active: 'true', prerequisites: '' },
  { code: 'POLS 102', title: 'Fundamentals of Political Theory', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Classical and contemporary theories of governance and justice', is_active: 'true', prerequisites: '' },
  { code: 'POLS 103', title: 'Philippine National Government and Constitution', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Structure of Philippine state executive legislative and judicial branches', is_active: 'true', prerequisites: '' },
  { code: 'POLS 104', title: 'Introduction to Comparative Politics', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Comparative analysis of political systems and regime types', is_active: 'true', prerequisites: 'POLS 101:Required:2.0' },
  { code: 'POLS 201', title: 'Ancient and Medieval Political Thought', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Political philosophies of Plato Aristotle Cicero St Augustine and Aquinas', is_active: 'true', prerequisites: 'POLS 102:Required:2.0' },
  { code: 'POLS 202', title: 'Modern Political Thought', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Machiavelli Hobbes Locke Rousseau Marx and Mill political doctrines', is_active: 'true', prerequisites: 'POLS 201:Required:2.0' },
  { code: 'POLS 203', title: 'Introduction to International Relations', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Realism liberalism constructivism and global state interactions', is_active: 'true', prerequisites: 'POLS 101:Required:2.0' },
  { code: 'POLS 204', title: 'Public Administration and Governance', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Bureaucracy administrative processes and public sector management', is_active: 'true', prerequisites: 'POLS 103:Required:2.0' },
  { code: 'POLS 205', title: 'Politics and Governance of Southeast Asia', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'ASEAN member states political dynamics and regional integration', is_active: 'true', prerequisites: 'POLS 104:Required:2.0' },
  { code: 'POLS 206', title: 'Research Methods in Political Science', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Research design qualitative and quantitative methodologies in political science', is_active: 'true', prerequisites: 'POLS 101:Required:2.0' },
  { code: 'POLS 301', title: 'Contemporary Political Thought', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Post-modernism critical theory post-colonialism and modern justice theory', is_active: 'true', prerequisites: 'POLS 202:Required:2.0' },
  { code: 'POLS 302', title: 'Philippine Foreign Policy', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Diplomatic history bilateral relations and foreign policy formulation in PH', is_active: 'true', prerequisites: 'POLS 203:Required:2.0' },
  { code: 'POLS 303', title: 'International Law and Organizations', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'United Nations international courts treaties and customary international law', is_active: 'true', prerequisites: 'POLS 203:Required:2.0' },
  { code: 'POLS 304', title: 'Political Parties and Elections', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Electoral systems campaign finance voter behavior and party dynamics', is_active: 'true', prerequisites: 'POLS 103:Required:2.0' },
  { code: 'POLS 305', title: 'Local Government and Autonomous Regions', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Local Government Code decentralization and regional autonomy (BARMM)', is_active: 'true', prerequisites: 'POLS 204:Required:2.0' },
  { code: 'POLS 306', title: 'Quantitative Analysis in Political Science', department_code: 'AB POLSCI', course_type_code: 'LECTURE_LAB', lecture_units: '2', laboratory_units: '1', credit_hours: '3', description: 'Statistical data analysis survey research and polling data modeling', is_active: 'true', prerequisites: 'POLS 206:Required:2.0' },
  { code: 'POLS 307', title: 'Qualitative Research Methods in Politics', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Case study analysis discourse analysis interviewing and archival research', is_active: 'true', prerequisites: 'POLS 206:Required:2.0' },
  { code: 'POLS 308', title: 'Policy Analysis and Evaluation', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Public policy formulation cost-benefit analysis and program evaluation', is_active: 'true', prerequisites: 'POLS 204:Required:2.0' },
  { code: 'POLS 401', title: 'Political Science Thesis 1', department_code: 'AB POLSCI', course_type_code: 'THESIS', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Thesis proposal formulation literature review and methodological design', is_active: 'true', prerequisites: 'POLS 206:Required:2.0' },
  { code: 'POLS 402', title: 'Political Science Thesis 2', department_code: 'AB POLSCI', course_type_code: 'THESIS', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Thesis completion empirical investigation and oral defense', is_active: 'true', prerequisites: 'POLS 401:Required:2.0' },
  { code: 'POLS 403', title: 'Practicum / Public Sector Internship', department_code: 'AB POLSCI', course_type_code: 'OJT', lecture_units: '0', laboratory_units: '3', credit_hours: '3', description: 'Fieldwork placement in government offices NGOs or diplomatic missions', is_active: 'true', prerequisites: 'POLS 308:Required:2.0' },
  { code: 'POLS 404', title: 'Human Rights and International Humanitarian Law', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Universal Declaration of Human Rights Geneva Conventions and transitional justice', is_active: 'true', prerequisites: 'POLS 303:Required:2.0' },
  { code: 'POLS 405', title: 'Political Economy of Development', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'State-market relations economic development models and global inequality', is_active: 'true', prerequisites: 'POLS 203:Required:2.0' },
  { code: 'POLS 406', title: 'Geopolitics and Global Security', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Maritime security South China Sea disputes cyber warfare and strategic doctrine', is_active: 'true', prerequisites: 'POLS 302:Required:2.0' },
  { code: 'POLS 407', title: 'Constitutional Law and Judicial Review', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Supreme Court jurisprudence fundamental rights and constitutional litigation', is_active: 'true', prerequisites: 'POLS 103:Required:2.0' },
  { code: 'POLS 408', title: 'Environmental Politics and Governance', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Climate change agreements sustainable development and environmental advocacy', is_active: 'true', prerequisites: '' },
  { code: 'POLS 409', title: 'Gender and Development Politics', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Feminist political theory gender mainstreaming and reproductive health policy', is_active: 'true', prerequisites: '' },
  { code: 'POLS 410', title: 'Diplomacy and Conflict Resolution', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Negotiation mediation peacebuilding and international dispute settlement', is_active: 'true', prerequisites: 'POLS 203:Required:2.0' },
  { code: 'POLS 411', title: 'Public Policy and Social Justice', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Poverty alleviation social protection programs and indigenous rights policy', is_active: 'true', prerequisites: 'POLS 308:Required:2.0' },
  { code: 'POLS 412', title: 'Special Topics in Political Science', department_code: 'AB POLSCI', course_type_code: 'LECTURE', lecture_units: '3', laboratory_units: '0', credit_hours: '3', description: 'Seminar on emerging issues in global and local politics', is_active: 'true', prerequisites: '' }
];

async function createAllCourses() {
  console.log(`Starting bulk import of ${coursesToCreate.length} courses via fn_bulk_create_courses...`);
  const jsonParam = JSON.stringify(coursesToCreate);
  
  const res = await runQuery(
    `SELECT public.fn_bulk_create_courses($1::jsonb) as result;`,
    [jsonParam]
  );

  const result = res.rows[0].result;
  console.log('Result:', JSON.stringify(result, null, 2));

  // Verify per department counts
  const counts = await runQuery(`
    SELECT d.code as department_code, d.name as department_name, COUNT(c.id) as course_count
    FROM public.departments d
    LEFT JOIN public.courses c ON c.department_id = d.id AND c.deleted_at IS NULL
    GROUP BY d.id, d.code, d.name
    ORDER BY d.code;
  `);

  console.log('\n--- COURSES COUNT PER DEPARTMENT ---');
  console.table(counts.rows);
}

createAllCourses().catch(console.error);
